name: cd

on:
  push:
    branches: [main]

jobs: 
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Gosec
        run: gosec ./...

      - name: Version
        run: (go version)
      
      - name: Deploy
        run: (./scripts/buildprod.sh)
